is_section=true

[[pages]]
path = "streamlit_app.py"
name = "Home"
icon = "ğŸ¡"

[[pages]]
path = "pages/task1.py"
name = "Task 1"
icon = "ğŸ“"

[[pages]]
path = "pages/task2.py"
name = "Task 2"
icon = "ğŸ“"