[[pages]]
path = "streamlit_app.py"
name = "Home"
icon = "ğŸ¡"

[[pages]]
name = "Tasks"
icon = "ğŸ–¥ï¸"
is_section = true

[[pages]]
path = "pages/task1.py"
name = "Task 1"
icon = "ğŸ“"
in_section = true

[[pages]]
path = "pages/task2.py"
name = "Task 2"
icon = "ğŸ“"
in_section = true

[[pages]]
path = "pages/task3.py"
name = "Task 3"
icon = "ğŸ“"
in_section = true

[[pages]]
path = "pages/task4.py"
name = "Task 4"
icon = "ğŸ“"
in_section = true